<!doctype html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Simps - A simple PHP MVC framework</title>
	<link rel="stylesheet" href="/assets/css/styles.css"/>
</head>
<body>
	<header>
		<h1>Simps Admin</h1>
		<p>Simps is a simple PHP MVC framework with DB and templating built in.</p>
	</header>
	<article>
		<?php echo $this->content; ?>
	</article>

<script src="/assets/js/scripts.js"></script>
</body>
</html>